#' @title Mock REDCap project
#'
#' @description
#' A fully synthetic REDCap-shaped project list used in package examples,
#' vignettes, and tests. The project is longitudinal and includes
#' demographics, follow-up, checkbox, validation, completion status, and
#' repeating instrument fields.
#'
#' @format A list with REDCap API-like data frames:
#' \describe{
#'   \item{data}{Synthetic REDCap records.}
#'   \item{metadata}{Synthetic REDCap data dictionary metadata.}
#'   \item{events}{Synthetic longitudinal event metadata.}
#'   \item{event_instruments}{Synthetic event-instrument mapping.}
#'   \item{instruments}{Synthetic instrument labels.}
#'   \item{repeating_instruments}{Synthetic repeating instrument settings.}
#'   \item{project_info}{Synthetic project-level metadata.}
#' }
#' @source Generated by `data-raw/mock-data.R`.
"mock_redcap_project"

#' @title Mock Record Status Dashboard data
#'
#' @description
#' A synthetic dashboard tile table generated from `mock_redcap_project` with
#' REDCapExploreR's internal record-status logic. This dataset is suitable for
#' examples of [plot_record_status()].
#'
#' @format A tibble with one row per record, event, and form tile.
#' @source Generated by `data-raw/mock-data.R`.
"mock_record_status_data"

#' @title Mock REDCap codebook
#'
#' @description
#' A synthetic `redcap_codebook` object generated from `mock_redcap_project`
#' with REDCapExploreR's internal codebook logic.
#'
#' @format A `redcap_codebook` list with `fields`, `choices`, `forms`, `events`,
#'   `event_instruments`, `repeating`, and `project` elements.
#' @source Generated by `data-raw/mock-data.R`.
"mock_codebook"

#' @title Mock REDCap quality report
#'
#' @description
#' A synthetic `redcap_quality_report` object generated from
#' `mock_redcap_project` with REDCapExploreR's internal quality-report logic.
#'
#' @format A `redcap_quality_report` list with `findings`, `summaries`, and
#'   `metadata` elements.
#' @source Generated by `data-raw/mock-data.R`.
"mock_quality_report"
